import { readFile, writeFile } from "node:fs/promises";

const outputPath = new URL("../YoutubeScript.js", import.meta.url);
const commentModulePath = new URL("../comment_mutations.js", import.meta.url);
const reactionModulePath = new URL("../video_reactions.js", import.meta.url);
const marker = "// BEGIN GENERATED NATIVE PLATFORM COMMENT MODULES";

const currentOutput = await readFile(outputPath, "utf8");
const base = currentOutput.split(marker, 1)[0].trimEnd();
const commentModule = (await readFile(commentModulePath, "utf8")).trim();
const reactionModule = (await readFile(reactionModulePath, "utf8")).trim();
const generated = [
    base,
    "",
    marker,
    "// Generated by scripts/embed-modules.mjs. Do not edit this section directly.",
    commentModule,
    "",
    reactionModule,
    ""
].join("\n");

await writeFile(outputPath, generated, "utf8");
